"""baseline — stamps the complete pre-v5 schema as it exists today (commit ad25ee5).

Generated via `alembic revision --autogenerate` against the unmodified pre-v5 models (backend
temporarily reverted to that state to produce this file cleanly), then diffed by hand against
`Base.metadata.create_all()`'s output to confirm zero drift. On a fresh database this creates
the schema; on an existing pre-Alembic database this revision is stamped, never executed — see
`app/db_bootstrap.py::ensure_schema_current()` and the Program Engine v5 plan, Milestone 1A.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-22 16:19:46.474361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('addresses_stations', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athletes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('tested_max_hr', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('experience_tier', sa.String(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('predicted_5k_seconds', sa.Integer(), nullable=True),
    sa.Column('current_10k_seconds', sa.Integer(), nullable=True),
    sa.Column('self_reported_weak_stations', sa.JSON(), nullable=False),
    sa.Column('goal_time_seconds', sa.Integer(), nullable=True),
    sa.Column('goal_event_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_email'), 'athletes', ['email'], unique=True)
    op.create_table('exercise_references',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cues', sa.JSON(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('station_reference',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance_or_reps', sa.String(), nullable=False),
    sa.Column('division_loads', sa.JSON(), nullable=False),
    sa.Column('primary_demand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('sensitivities', sa.JSON(), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    op.create_table('past_hyrox_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('station_splits_seconds', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_readings_athlete_id'), 'recovery_readings', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_recovery_readings_reading_date'), 'recovery_readings', ['reading_date'], unique=False)
    op.create_table('recovery_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(), nullable=False),
    sa.Column('hrv_z', sa.Float(), nullable=True),
    sa.Column('resting_hr_z', sa.Float(), nullable=True),
    sa.Column('sleep_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_scores_athlete_id'), 'recovery_scores', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_recovery_scores_score_date'), 'recovery_scores', ['score_date'], unique=False)
    op.create_table('training_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('length_weeks', sa.Integer(), nullable=False),
    sa.Column('goal_event_date', sa.Date(), nullable=True),
    sa.Column('goal_time_seconds', sa.Integer(), nullable=True),
    sa.Column('target_weaknesses', sa.JSON(), nullable=False),
    sa.Column('deload_week_numbers', sa.JSON(), nullable=False),
    sa.Column('taper_week_numbers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_blocks_athlete_id'), 'training_blocks', ['athlete_id'], unique=False)
    op.create_table('wearable_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_guidance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_guidance_profile_id'), 'nutrition_guidance', ['profile_id'], unique=False)
    op.create_table('training_weeks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('planned_intensity', sa.Float(), nullable=False),
    sa.Column('actual_intensity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['training_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_weeks_block_id'), 'training_weeks', ['block_id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('week_id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prescription', sa.JSON(), nullable=False),
    sa.Column('logged_result', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['training_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_week_id'), 'workouts', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_week_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_training_weeks_block_id'), table_name='training_weeks')
    op.drop_table('training_weeks')
    op.drop_index(op.f('ix_nutrition_guidance_profile_id'), table_name='nutrition_guidance')
    op.drop_table('nutrition_guidance')
    op.drop_table('wearable_connections')
    op.drop_index(op.f('ix_training_blocks_athlete_id'), table_name='training_blocks')
    op.drop_table('training_blocks')
    op.drop_index(op.f('ix_recovery_scores_score_date'), table_name='recovery_scores')
    op.drop_index(op.f('ix_recovery_scores_athlete_id'), table_name='recovery_scores')
    op.drop_table('recovery_scores')
    op.drop_index(op.f('ix_recovery_readings_reading_date'), table_name='recovery_readings')
    op.drop_index(op.f('ix_recovery_readings_athlete_id'), table_name='recovery_readings')
    op.drop_table('recovery_readings')
    op.drop_table('past_hyrox_results')
    op.drop_table('nutrition_profiles')
    op.drop_table('station_reference')
    op.drop_table('exercise_references')
    op.drop_index(op.f('ix_athletes_email'), table_name='athletes')
    op.drop_table('athletes')
    op.drop_table('accessory_movements')
    # ### end Alembic commands ###
